### PR TITLE
Fix metadata

### PR DESCRIPTION
**Pull request by cgranade**
This PR ensures that metadata in messages and display data are always well-formed JSON objects, rather than `null` or string-valued.

### CODE REVIEW

**Review by anpaz — APPROVED** [review]
Changes lgtm.
This is probably a breaking change (due to the change in the Metadata signature) so we should probably upgrade the build major too.

**Comment by cgranade** [comment]
> Changes lgtm. This is probably a breaking change (due to the change in the Metadata signature) so we should probably upgrade the build major too.

Thanks for your review! Agreed about updating the version number, I hadn't thought of it as breaking but you're absolutely right. Thanks for catching that!

**Comment by cgranade** [comment]
Merging as signed pipeline has passed.

**Pull request merged**
